"""modified seeking venues,talent in artist and venues

Revision ID: 059435d4e7a7
Revises: e46cd08e0adb
Create Date: 2020-11-23 12:36:51.481931

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '059435d4e7a7'
down_revision = 'e46cd08e0adb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('seeking_description', sa.String(length=500), nullable=True))
    op.add_column('Artist', sa.Column('seeking_venue', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Artist', 'seeking_venue')
    op.drop_column('Artist', 'seeking_description')
    # ### end Alembic commands ###
